name: CI

on:
  - pull_request

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and Test
  #  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  #  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - uses: volta-cli/action@v1

      - name: Install dependencies
        run: npm install

      - name: Check
        run: npm run check